"""Batch-generate AI practice MCQs for PFRDA/EPFO, persisted into `pyq_bank`
(`source_type='ai_generated'`) — not the live, ephemeral per-session generation Devthorium's
unmerged PR #58 built. That approach throws every generated question away after the
session; this one builds a real, reusable, indexed bank in the same place real PYQs live,
so it's servable through the exact same API/drill UI with zero new query surface.

Grounding: real PYQ text pulled straight from this DB's own `pyq_bank` (never the model's
training knowledge alone — PFRDA/EPFO are niche exams, same reasoning as
generate_dimensions_from_pyqs.py's DECIDE-37) plus the per-topic testable "dimensions"
already derived from real PYQ evidence (data/dimensions/{exam_id}.json). That file is
generated by, and lives in, the sibling Devthorium repo
(scripts/generate_dimensions_from_pyqs.py there) — a documented cross-repo read, same
pattern this project's own CLAUDE.md already uses for referencing ../Devthorium.

Trust model, made explicit: `pyq_bank.status` means "matched a real official answer key"
for real PYQs (DECIDE-26/27 — never LLM-guessed). For `source_type='ai_generated'` rows
the model authors question AND answer together — a different, legitimate category, not a
guess about an unknown real answer. New rows insert as status='unverified'; a human spot
-check (scripts/review_ai_questions.py) can promote one to 'verified' or 'void'. Every
consumer must key trust semantics off `source_type`, never assume 'verified' alone means
"official key" the way it does for source_type in ('official_pyq', 'coaching_derived').

Idempotent: counts existing ai_generated rows per (topic_id, dimension_id) via the new
`ai_question_dimensions` link table and only generates the shortfall — a rerun tops up
coverage, it never duplicates.

Usage:
    .venv/bin/python scripts/generate_ai_pyq_bank.py --exam_id pfrda_gradea --topic_id pfrda_costing --dry_run
    .venv/bin/python scripts/generate_ai_pyq_bank.py --exam_id pfrda_gradea --topic_id pfrda_costing
    .venv/bin/python scripts/generate_ai_pyq_bank.py --exam_id pfrda_gradea --max_topics 10
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sqlite3
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

import anthropic
from dotenv import load_dotenv
from pydantic import BaseModel, ValidationError, field_validator

PROJECT_ROOT = Path(__file__).parent.parent
load_dotenv(PROJECT_ROOT / ".env")

DB_PATH = PROJECT_ROOT / "data" / "core.db"
PROMPT_PATH = PROJECT_ROOT / "prompts" / "ai_pyq_bank_quiz.txt"
DIMENSIONS_DIR = PROJECT_ROOT.parent / "Devthorium" / "data" / "dimensions"

MODEL = os.getenv("AI_MODEL_SMART", "claude-sonnet-5")
RETRY_LIMIT = 3
RETRY_DELAY = 5
OVERLAP_REJECT_THRESHOLD = 0.75  # normalized token overlap -> reject as too-similar

EXAM_NAMES = {
    "pfrda_gradea": "PFRDA Grade A",
    "upsc_epfo_apfc_eo_ao": "UPSC EPFO — APFC / EO-AO",
}

API_KEY = os.getenv("ANTHROPIC_API_KEY")
if not API_KEY:
    print("ERROR: ANTHROPIC_API_KEY not set. Check .env at project root.")
    sys.exit(1)


class GeneratedMCQ(BaseModel):
    question_text: str
    option_a: str
    option_b: str
    option_c: str
    option_d: str
    correct_answer: str
    concept_summary: str
    options_rationale: dict[str, str]
    elimination_strategy: str | None = None
    topic_id: str
    dimension_id: str
    difficulty: str

    @field_validator("correct_answer")
    @classmethod
    def _valid_letter(cls, v: str) -> str:
        v = v.strip().lower()
        if v not in ("a", "b", "c", "d"):
            raise ValueError(f"correct_answer must be a/b/c/d, got {v!r}")
        return v


def load_dimensions(exam_id: str) -> list[dict]:
    path = DIMENSIONS_DIR / f"{exam_id}.json"
    if not path.exists():
        print(f"ERROR: dimension file not found: {path}\n"
              "Run Devthorium's scripts/generate_dimensions_from_pyqs.py first.")
        sys.exit(1)
    return json.loads(path.read_text())


def fetch_real_pyq_examples(conn: sqlite3.Connection, exam_id: str, topic_id: str, limit: int = 8) -> list[sqlite3.Row]:
    """Only genuinely well-formed real MCQs — same >=4-option validity rule the Devthorium
    drill enforces at serving time (found live, 2026-09-18: ~35% of PFRDA's real rows have
    broken/single-option data and must never be used as a style example)."""
    rows = conn.execute(
        """SELECT question_text, options, year FROM pyq_bank
           WHERE exam_id = ? AND topic_id = ? AND question_format = 'mcq'
             AND source_type != 'ai_generated' AND status != 'void' AND options IS NOT NULL""",
        (exam_id, topic_id),
    ).fetchall()
    good = []
    for r in rows:
        try:
            opts = json.loads(r["options"])
        except (TypeError, json.JSONDecodeError):
            continue
        if isinstance(opts, dict) and len(opts) >= 4:
            good.append(r)
    return good[:limit]


def format_real_pyq_examples(rows: list[sqlite3.Row]) -> str:
    if not rows:
        return "None available."
    lines = []
    for i, r in enumerate(rows, 1):
        opts = json.loads(r["options"])
        opt_str = "  ".join(f"{k}) {v}" for k, v in sorted(opts.items()))
        year = f" ({r['year']})" if r["year"] else ""
        lines.append(f"{i}.{year} {r['question_text']}\n   {opt_str}")
    return "\n\n".join(lines)


def fetch_existing_ai_question_texts(conn: sqlite3.Connection, topic_id: str, limit: int = 30) -> list[str]:
    rows = conn.execute(
        "SELECT question_text FROM pyq_bank WHERE topic_id = ? AND source_type = 'ai_generated' "
        "ORDER BY question_id DESC LIMIT ?",
        (topic_id, limit),
    ).fetchall()
    return [r[0] for r in rows]


def existing_ai_count_for_dimension(conn: sqlite3.Connection, dimension_id: str) -> int:
    row = conn.execute(
        "SELECT COUNT(*) FROM ai_question_dimensions WHERE dimension_id = ?", (dimension_id,)
    ).fetchone()
    return row[0]


def _tokens(text: str) -> set[str]:
    return set(re.findall(r"[a-z0-9]+", text.lower()))


def is_too_similar(question_text: str, existing_texts: list[str]) -> bool:
    tq = _tokens(question_text)
    if not tq:
        return False
    for t in existing_texts:
        tt = _tokens(t)
        if not tt:
            continue
        overlap = len(tq & tt) / min(len(tq), len(tt))
        if overlap >= OVERLAP_REJECT_THRESHOLD:
            return True
    return False


def build_prompt(exam_name: str, topic: dict, dimension: dict, n_needed: int,
                  real_examples_str: str, existing_texts: list[str]) -> str:
    template = PROMPT_PATH.read_text()
    return (
        template
        .replace("{{exam_name}}", exam_name)
        .replace("{{topic_name}}", topic["name"])
        .replace("{{topic_id}}", topic["topic_id"])
        .replace("{{dimension_name}}", dimension["name"])
        .replace("{{dimension_id}}", dimension["id"])
        .replace("{{num_questions}}", str(n_needed))
        .replace("{{real_pyq_examples}}", real_examples_str)
        .replace("{{existing_ai_question_texts}}",
                 "; ".join(t[:80] for t in existing_texts[:20]) or "None yet.")
    )


class InsufficientCreditsError(RuntimeError):
    """The Anthropic account has no balance left -- found live, 2026-09-18: a full-scale
    run silently burned ~300 slots' worth of 3x-retried, guaranteed-to-fail calls after
    hitting this (BadRequestError, non-retryable) before it was noticed and killed
    manually. Retrying never helps here, and neither does continuing to the next slot --
    the whole run must stop immediately so this doesn't happen silently again."""


def call_model(client: anthropic.Anthropic, prompt: str) -> tuple[str, dict]:
    last_exc: Exception | None = None
    for attempt in range(RETRY_LIMIT):
        try:
            # 8192, not 4096: found live -- claude-sonnet-5 emits a leading ThinkingBlock
            # that competes with the JSON output for the same max_tokens budget, and 4096
            # was too tight (2/5 pilot calls truncated before any JSON closed, BUG-14's
            # exact failure class from real ingestion).
            response = client.messages.create(
                model=MODEL, max_tokens=8192, messages=[{"role": "user", "content": prompt}]
            )
            usage = {
                "input_tokens": response.usage.input_tokens,
                "output_tokens": response.usage.output_tokens,
            }
            # claude-sonnet-5 can return a leading ThinkingBlock before the text block —
            # find the actual text block instead of assuming content[0] (found live).
            text_block = next((b for b in response.content if b.type == "text"), None)
            if text_block is None:
                raise RuntimeError("no text block in response content")
            return text_block.text.strip(), usage
        except anthropic.BadRequestError as exc:
            if "credit balance" in str(exc).lower():
                raise InsufficientCreditsError(str(exc)) from exc
            raise RuntimeError(f"Bad request (not retryable): {exc}") from exc
        except anthropic.APIError as exc:
            last_exc = exc
            if attempt < RETRY_LIMIT - 1:
                time.sleep(RETRY_DELAY)
    raise RuntimeError(f"Anthropic API failed after {RETRY_LIMIT} attempts: {last_exc}")


def parse_and_validate(raw: str, topic_id: str, dimension_id: str,
                        existing_texts: list[str]) -> list[GeneratedMCQ]:
    start, end = raw.find("["), raw.rfind("]") + 1
    if start == -1 or end == 0:
        print(f"  FLAGGED: no JSON array found in response for {topic_id}/{dimension_id} "
              f"(raw tail: ...{raw[-200:]!r})")
        return []
    try:
        parsed = json.loads(raw[start:end])
    except json.JSONDecodeError as exc:
        print(f"  FLAGGED: JSON parse failure for {topic_id}/{dimension_id}: {exc} "
              f"(raw tail: ...{raw[-200:]!r})")
        return []

    accepted: list[GeneratedMCQ] = []
    for item in parsed:
        try:
            mcq = GeneratedMCQ.model_validate(item)
        except ValidationError as exc:
            print(f"  FLAGGED: schema validation failed: {exc.error_count()} error(s)")
            continue
        if mcq.topic_id != topic_id or mcq.dimension_id != dimension_id:
            print(f"  FLAGGED: topic/dimension drift ({mcq.topic_id}/{mcq.dimension_id})")
            continue
        if is_too_similar(mcq.question_text, existing_texts):
            print("  FLAGGED: too similar to existing/real content, skipped")
            continue
        accepted.append(mcq)
        existing_texts.append(mcq.question_text)  # avoid intra-batch dupes too
    return accepted


def write_question(conn: sqlite3.Connection, exam_id: str, mcq: GeneratedMCQ, seq: int) -> str:
    question_id = f"{mcq.topic_id}_ai_{mcq.dimension_id}_{seq}"
    options = {"A": mcq.option_a, "B": mcq.option_b, "C": mcq.option_c, "D": mcq.option_d}
    correct_letter = mcq.correct_answer.upper()

    conn.execute(
        """INSERT OR IGNORE INTO pyq_bank
           (question_id, exam_id, paper_id, topic_id, question_format, year, question_text,
            options, correct_option, status, source_type)
           VALUES (?, ?, NULL, ?, 'mcq', NULL, ?, ?, ?, 'unverified', 'ai_generated')""",
        (question_id, exam_id, mcq.topic_id, mcq.question_text, json.dumps(options), correct_letter),
    )
    conn.execute(
        "INSERT OR IGNORE INTO ai_question_dimensions (question_id, dimension_id) VALUES (?, ?)",
        (question_id, mcq.dimension_id),
    )

    rationale = mcq.options_rationale or {}
    detail = {
        "option_format": "standalone",
        "options": [
            {
                "option_label": letter,
                "option_text": options[letter],
                "is_correct": letter == correct_letter,
                "rationale": rationale.get(letter.lower(), rationale.get(letter, "")),
            }
            for letter in ("A", "B", "C", "D")
        ],
    }
    conn.execute(
        """INSERT OR IGNORE INTO pyq_explanations
           (question_id, concept_summary, detail, elimination_strategy, grounding_chunk_ids,
            model_version, generated_at)
           VALUES (?, ?, ?, ?, '[]', ?, ?)""",
        (question_id, mcq.concept_summary, json.dumps(detail), mcq.elimination_strategy,
         MODEL, datetime.now(timezone.utc).isoformat()),
    )
    return question_id


@dataclass
class WorkItem:
    topic: dict
    dimension: dict
    n_needed: int
    real_examples_str: str
    existing_texts: list[str] = field(default_factory=list)
    existing_count: int = 0


def build_work_items(conn: sqlite3.Connection, exam_id: str, topics: list[dict],
                      n_per_dimension: int, force: bool) -> list[WorkItem]:
    """Pure read/preparation pass — no network calls — so the slow model-calling phase
    can run concurrently afterward without any shared-connection threading concerns."""
    items: list[WorkItem] = []
    for topic in topics:
        topic_id = topic["topic_id"]
        dims = topic.get("dimensions", [])
        if topic.get("insufficient_pyq_evidence") and not force:
            print(f"SKIP {topic_id}: insufficient_pyq_evidence (use --force to override)")
            continue
        if not dims:
            continue

        real_examples_str = format_real_pyq_examples(fetch_real_pyq_examples(conn, exam_id, topic_id))
        # Snapshot at prep time -- concurrent sibling-dimension calls for the same topic
        # won't see each other's freshly-generated text, a minor, acceptable trade-off
        # (different dimensions target different testable angles anyway; the real hard
        # duplicate guard is parse_and_validate's per-item token-overlap rejection).
        existing_texts = fetch_existing_ai_question_texts(conn, topic_id)

        for dim in dims:
            existing_count = existing_ai_count_for_dimension(conn, dim["id"])
            n_needed = n_per_dimension - existing_count
            if n_needed > 0:
                items.append(WorkItem(topic, dim, n_needed, real_examples_str, list(existing_texts), existing_count))
    return items


def generate_one(client: anthropic.Anthropic, exam_name: str, item: WorkItem) -> tuple[WorkItem, list, dict, str | None]:
    """Runs in a worker thread: pure model call + parse/validate, no DB access."""
    prompt = build_prompt(exam_name, item.topic, item.dimension, item.n_needed,
                           item.real_examples_str, item.existing_texts)
    try:
        raw, usage = call_model(client, prompt)
    except InsufficientCreditsError:
        raise  # let this propagate -- caller must stop the whole run, not just this item
    except RuntimeError as exc:
        return item, [], {"input_tokens": 0, "output_tokens": 0}, str(exc)
    accepted = parse_and_validate(raw, item.topic["topic_id"], item.dimension["id"], item.existing_texts)
    return item, accepted, usage, None


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exam_id", required=True, choices=list(EXAM_NAMES))
    parser.add_argument("--topic_id", default=None, help="restrict to one topic; default = all")
    parser.add_argument("--n_per_dimension", type=int, default=6)
    parser.add_argument("--max_topics", type=int, default=None,
                         help="cap how many topics to process this run (priority order)")
    parser.add_argument("--force", action="store_true",
                         help="also generate for topics flagged insufficient_pyq_evidence")
    parser.add_argument("--concurrency", type=int, default=6,
                         help="parallel model calls -- pure network work, no shared DB connection")
    parser.add_argument("--dry_run", action="store_true", help="call the model, print results, write nothing")
    args = parser.parse_args()

    client = anthropic.Anthropic(api_key=API_KEY)
    dimensions_data = load_dimensions(args.exam_id)

    if args.topic_id:
        topics = [t for t in dimensions_data if t["topic_id"] == args.topic_id]
        if not topics:
            print(f"ERROR: topic_id {args.topic_id!r} not found in {args.exam_id}'s dimension file")
            sys.exit(1)
    else:
        # Highest-weight, thinnest-real-coverage topics first — the topics most worth
        # supplementing, not an arbitrary file order.
        topics = sorted(dimensions_data,
                         key=lambda t: t.get("real_pyq_count", 0) / max(t.get("weight", 1.0), 0.01))
        if args.max_topics:
            topics = topics[: args.max_topics]

    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON;")
    conn.row_factory = sqlite3.Row

    exam_name = EXAM_NAMES[args.exam_id]
    work_items = build_work_items(conn, args.exam_id, topics, args.n_per_dimension, args.force)
    print(f"\n{len(work_items)} (topic, dimension) slots to generate, concurrency={args.concurrency}.\n")

    total_written = total_flagged = 0
    total_usage = {"input_tokens": 0, "output_tokens": 0}

    stopped_early = False
    with ThreadPoolExecutor(max_workers=args.concurrency) as pool:
        futures = {pool.submit(generate_one, client, exam_name, item): item for item in work_items}
        for i, future in enumerate(as_completed(futures), start=1):
            item = futures[future]
            topic_id, dim_id = item.topic["topic_id"], item.dimension["id"]
            try:
                _, accepted, usage, error = future.result()
            except InsufficientCreditsError as exc:
                print(f"\nSTOPPED: Anthropic account has no credit balance left ({exc}).\n"
                      "Add credits, then rerun this exact command — it's idempotent and "
                      "will pick up exactly where it left off, nothing is lost.")
                for f in futures:
                    f.cancel()  # only cancels not-yet-started futures; in-flight ones finish quietly
                stopped_early = True
                break
            except Exception as exc:  # noqa: BLE001 -- a worker crash must not kill the whole run
                print(f"[{i}/{len(work_items)}] {topic_id} / {dim_id}: WORKER ERROR: {exc}")
                total_flagged += item.n_needed
                continue

            total_usage["input_tokens"] += usage["input_tokens"]
            total_usage["output_tokens"] += usage["output_tokens"]

            if error:
                print(f"[{i}/{len(work_items)}] {topic_id} / {dim_id}: ERROR: {error}")
                total_flagged += item.n_needed
                continue

            total_flagged += max(item.n_needed - len(accepted), 0)
            print(f"[{i}/{len(work_items)}] {topic_id} / {dim_id}: {len(accepted)}/{item.n_needed} accepted")

            if args.dry_run:
                for mcq in accepted:
                    print(f"  [DRY RUN] {mcq.question_text}")
                    print(f"    A) {mcq.option_a}  B) {mcq.option_b}  C) {mcq.option_c}  D) {mcq.option_d}")
                    print(f"    Correct: {mcq.correct_answer.upper()}  |  {mcq.concept_summary}")
                continue

            seq = item.existing_count
            for mcq in accepted:
                seq += 1
                write_question(conn, args.exam_id, mcq, seq)
                total_written += 1
            conn.commit()

    conn.close()

    input_cost = total_usage["input_tokens"] / 1_000_000 * 3.0
    output_cost = total_usage["output_tokens"] / 1_000_000 * 15.0
    status = "STOPPED EARLY (out of credits)" if stopped_early else "Done"
    print(f"\n{status}. {total_written} AI questions written, {total_flagged} generation slots flagged/rejected"
          f" out of {len(work_items)} total.")
    print(f"Usage: {total_usage['input_tokens']} input, {total_usage['output_tokens']} output tokens "
          f"(~${input_cost + output_cost:.2f} est., Sonnet pricing).")


if __name__ == "__main__":
    main()
